spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:springws;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
